name: Validate action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: karlis-vagalis/doxxer-action@v0.7.0
        with:
          command: current

      - uses: karlis-vagalis/doxxer-action@v0.7.0
        with:
          command: next
