name: Validate action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: karlis-vagalis/doxxer-action@v0.7.0
        id: dc
        with:
          command: current

      - name: Print current version
        run: |
          echo "Current version output is: ${{ steps.dc.outputs.version }}"

      - uses: karlis-vagalis/doxxer-action@v0.7.0
        id: dn
        with:
          command: next

      - name: Print next version
        run: |
          echo "Next version output is: ${{ steps.dn.outputs.version }}"
